--FUNCTION TO FIND BIGGEEST OF TWO NUMBERS

CREATE OR REPLACE FUNCTION BIG1(NO1 IN NUMBER , NO2 IN NUMBER)
RETURN NUMBER IS 
BEGIN
    IF NO1 > NO2 THEN RETURN NO1;
    ELSE RETURN NO2;
    END IF;
END;
